# glcoud builds submit
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/smoketest', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/smoketest']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'smoketest', '--image',
         'gcr.io/$PROJECT_ID/smoketest', '--region', 'us-east4',
         '--platform', 'managed', '--allow-unauthenticated',
          '--set-env-vars=SLACK_URL=${_SLACK_URL}' ]
images:
- gcr.io/$PROJECT_ID/smoketest