name: forgeops_smoke_test
description: Run smoke tests on a deployed ForgeOps platform
version: 0.0.1
homepage: https://github.com/ForgeRock/forgeops

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.5.0
  shelf: ^0.7.5
  shelf_router: ^0.7.2
  shelf_static: ^0.2.8
  dio: ^3.0.9
  dio_cookie_manager: ^1.0.0
  http: ^0.12.1

dev_dependencies:
  pedantic: ^1.8.0
  test: any

